monolog:
    handlers:
        main:
            type: rotating_file
            # see services.yaml
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            # see services.yaml
            # level: debug
            channels: ["!event", "!doctrine", "!security"]
            # see services.yaml
            # max_files: 15

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        #doctrine:
        #    type: stream
        #    path: "%kernel.logs_dir%/doctrine.log"
        #    level: debug
        #    channels: ["doctrine"]
